### ISSUE TITLE
Detect even if delayed

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-detector#1]
There could be a case where react isn't rendered to the dom immediately ([for example](http://jsbin.com/nagim/1)). Figure out another way to more accurately determine if react running on the page. Perhaps poll every 1 second?

**Comment by kentcdodds** [comment]
Fixed by #2. Thanks @spicyj. Preparing a new release now.

**Comment by sophiebits** [comment]
Hah, didn't even see this issue.

**Comment by kentcdodds** [comment]
You should get the update soon :-)
