### ISSUE TITLE
Extension for firefox?

### ISSUE THREAD

**Issue by Manish-Giri** [kentcdodds/react-detector#10]
This works great on Chrome! Is there a version of this extension for Firefox, or any plans to build one? Thanks!

**Comment by kentcdodds** [comment]
I recommend the regular react DevTools extension. It does what this one can and more

**Comment by Manish-Giri** [comment]
Sorry, I created this issue without first looking at the readme document which links to a [firefox version](https://github.com/cymen/show-me-the-react). But I couldn't find the extension on Firefox.

Of course, the regular React DevTools is good, but I find this extension more efficient because it clearly highlights if a page is using React, after which you can explore it further in Dev Tools. There's no need to visit the dev tools extension only to find the page isn't using React at all.

Thanks again!

**Comment by kentcdodds** [comment]
Actually, React's devtools will show you whether the site is using react:

![](https://camo.githubusercontent.com/01f615b5602df550ff21d01b5481eb3c0568ccf9/687474703a2f2f692e696d6775722e636f6d2f3374756849676d2e706e67)

It'll even show you that the page is using the development version of react which is pretty neat :)

In any case, I'm not working on this project anymore, so I'll go ahead and close this :)
