### ISSUE TITLE
Add mode that shows the React elements on the page.

### ISSUE THREAD

**Issue by mihaip** [kentcdodds/react-detector#5]
When clicking on the icon, inject a style sheet that gives a green outline or other indicator of where the React components are. Facebook would look something like this:

![image](https://cloud.githubusercontent.com/assets/513813/6718507/67e6c22e-cd71-11e4-9f41-4182d5302e5b.png)

Happy to work on this, just wanted to make sure you were interested in this feature.

**Comment by kentcdodds** [comment]
Sounds cool. Looking forward to a PR. If it's ok with you, I'll wait to release your other PR until this one gets in too. Thanks!

**Comment by kentcdodds** [comment]
This has been published. You should get the update within the hour. Thanks for the PR!

![screen shot 2015-03-18 at 3 21 55 pm](https://cloud.githubusercontent.com/assets/1500684/6719770/ab99fa2a-cd82-11e4-9861-03f050b738e4.png)
