### ISSUE TITLE
Update detection to work with React v0.15.0

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-detector#7]
Because of [this](https://twitter.com/soprano/status/665275895955849216)

**Comment by mayankchd** [comment]
we can check for both [data-reactid] and [data-reactroot] and if anyone of them is present we can outline the components.

**Comment by kentcdodds** [comment]
I think we can use that to detect whether react is on the page, but with v0.15.0 there doesn't appear to be any way to identify an individual component from the DOM. So we wont be able to outline components in v0.15.0 :-(

**Comment by mayankchd** [comment]
Yup!  But it does outlines the container component  . I tried  , it's good enough until we find something else.
